version: '2.3'
services:

  #
  # Platform Data
  #
  # Get data from dockerhub to run various services
  #

  platform_data:
    container_name: jolibrain_platform_data
    image: jolibrain/platform_data:latest
    user: ${CURRENT_UID}
    volumes:
      - ${DD_PLATFORM}:/platform

  #
  # Platform UI
  #
  # Serving react container
  #

  platform_ui:
    container_name: jolibrain_platform_ui
    image: jolibrain/platform_ui:latest
    restart: always
    volumes:
      - platform_ui:/usr/share/nginx/html
      - ./config/platform_ui/config.json:/usr/share/nginx/html/config.json

  #
  # Deepdetect
  #

  deepdetect:
    container_name: jolibrain_deepdetect
    image: 'jolibrain/deepdetect_gpu'
    runtime: nvidia
    restart: always
    volumes:
      - ${DD_PLATFORM}:/opt/platform
      
  #
  # Deepdetect cpu
  #

  deepdetect_cpu:
    container_name: jolibrain_deepdetect_cpu
    image: 'jolibrain/deepdetect_cpu'
    restart: always
    cpu_count: 6
    volumes:
      - ${DD_PLATFORM}:/opt/platform


  #
  # nginx
  #
  # modify port 80 to change facade port
  #

  nginx:
    container_name: jolibrain_nginx
    image: nginx:latest
    restart: always
    ports:
      - '127.0.0.1:1912:80'
    links:
      - jupyter:jupyter
      - deepdetect:deepdetect
      - gpustat_server
      - filebrowser
    volumes:
      - platform_ui:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DD_PLATFORM}:/opt/platform
      - ./config/platform_ui/config.json:/var/www/html/config.json
      - ${DD_PLATFORM}/version.json:/var/www/html/version.json

  #
  # Jupyter notebooks
  #

  jupyter:
    container_name: jolibrain_jupyter
    environment:
      - JUPYTER_LAB_ENABLE=yes
      - NB_UID=${MUID}
    image: jolibrain/jupyter_dd_notebook
    volumes:
      - ${DD_PLATFORM}:/opt/platform
      - ${DD_PLATFORM}/notebooks:/home/jovyan/work
      - ./config/jupyter:/home/jovyan/.jupyter

  #
  # gpustat-server
  #
  gpustat_server:
    container_name: jolibrain_gpustat_server
    image:  jolibrain/gpustat_server
    runtime: nvidia

  #
  # filebrowser
  #
  filebrowser:
    container_name: jolibrain_filebrowser
    image: filebrowser/filebrowser:v1.10.0
    user: ${CURRENT_UID}
    volumes:
      - ${DD_PLATFORM}:/srv
      - ./config/filebrowser/database.db:/etc/database.db
      - ./config/filebrowser/config.json:/config.json

  #
  # container version monitoring for updates
  #
  ouroboros:
   container_name: jolibrain_ouroboros
   image: jolibrain/ouroboros
   environment:
     - INTERVAL=21600
     - LOG_LEVEL=info
     - DRY_RUN=true
     - FILE_PATH=/opt/version.json
     - MONITOR="jolibrain/platform_data jolibrain/platform_ui jolibrain/deepdetect_gpu nginx jolibrain/jupyter_dd_notebook filebrowser/filebrowser jolibrain/gpustat_server jolibrain/ouroboros"
   restart: always
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${DD_PLATFORM}:/opt

volumes:
  platform_ui:
